alias open=thunar
alias goremote="ssh supernova"
alias remote="cd ~/remote"
alias pubhtml="cd ~/remote/public_html"
alias denshock="~/remote/denshock/denshock.sh"
alias ds="denshock"
alias la="ls -a"
alias ll="ls -l"
alias lsa="ls -la"
